Listing 20.4 Related data in the SuppliersController.cs file in the Controllers folder
JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 32.